[project]
name = "gewr002-report-experiment"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pytest>=9.0.1",
]

[tool.pytest.ini_options]
markers = [
    "describe: custom description mark for test suites"
]
